/*  KingStation - A frontend for libks.
 *  Copyright (C) 2010-2014 - Hans-Kristian Arntzen
 *  Copyright (C) 2011-2016 - Daniel De Matteis
 *  Copyright (C) 2016-2019 - Brad Parker
 *
 *  KingStation is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  KingStation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with KingStation.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __CONFIG_DEF_KEYBINDS_H
#define __CONFIG_DEF_KEYBINDS_H

#ifndef IS_SALAMANDER

/* User 1 */
static const struct ks_keybind ks_keybinds_1[] = {
#ifdef __QNX__
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, KSK_l,
      KS_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, KSK_k,
      KS_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, KSK_q,
      KS_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, KSK_e,
      KS_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, KSK_w,
      KS_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, KSK_s,
      KS_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, KSK_a,
      KS_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, KSK_d,
      KS_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, KSK_l,
      KS_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, KSK_o,
      KS_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, KSK_CAPSLOCK,
      KS_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, KSK_SEMICOLON,
      KS_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, KSK_TAB,
      KS_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, KSK_p,
      KS_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_TRIGGER, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      KINGSN_LIGHTGUN_RELOAD,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, KSK_UNKNOWN,
      NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE, KSK_UNKNOWN,
      KINGSN_TURBO_ENABLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, KSK_UNKNOWN,
      KINGSN_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, KSK_UNKNOWN,
      KINGSN_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, KSK_UNKNOWN,
      KINGSN_VOLUME_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, KSK_UNKNOWN,
      KINGSN_VOLUME_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, KSK_UNKNOWN,
      KINGSN_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, KSK_UNKNOWN,
      KINGSN_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, KSK_UNKNOWN,  
      KINGSN_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, KSK_UNKNOWN,
      KINGSN_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, KSK_UNKNOWN,
      KINGSN_QUIT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, KSK_UNKNOWN,
      KINGSN_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, KSK_UNKNOWN,
      KINGSN_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, KSK_UNKNOWN,
      KINGSN_REWIND, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_BSV_RECORD_TOGGLE, KSK_UNKNOWN,
      KINGSN_BSV_RECORD_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, KSK_UNKNOWN,
      KINGSN_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, KSK_UNKNOWN,
      KINGSN_FRAMEADVANCE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, KSK_UNKNOWN,
      KINGSN_RESET, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, KSK_UNKNOWN,
      KINGSN_SHADER_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, KSK_UNKNOWN,
      KINGSN_SHADER_PREV, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, KSK_UNKNOWN,
      KINGSN_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, KSK_UNKNOWN,
      KINGSN_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, KSK_UNKNOWN,
      KINGSN_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, KSK_UNKNOWN,
      KINGSN_SCREENSHOT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, KSK_UNKNOWN,
      KINGSN_MUTE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, KSK_UNKNOWN,
      KINGSN_OSK, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, KSK_UNKNOWN,
      KINGSN_FPS_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SEND_DEBUG_INFO, KSK_UNKNOWN,
      KINGSN_SEND_DEBUG_INFO, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, KSK_UNKNOWN,
      KINGSN_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, KSK_UNKNOWN,
      KINGSN_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, KSK_UNKNOWN,
      KINGSN_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, KSK_UNKNOWN,
      KINGSN_OVERLAY_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, KSK_UNKNOWN,
      KINGSN_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, KSK_UNKNOWN,
      KINGSN_DISK_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, KSK_UNKNOWN,
      KINGSN_DISK_PREV, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, KSK_UNKNOWN,
      KINGSN_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, KSK_UNKNOWN,
      KINGSN_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, KSK_UNKNOWN,
      KINGSN_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, KSK_SPACE,
      KINGSN_MENU_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, KSK_UNKNOWN,
      KINGSN_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, KSK_UNKNOWN,
      KINGSN_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, KSK_UNKNOWN,
      KINGSN_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, KSK_UNKNOWN,
      KINGSN_AI_SERVICE, NO_BTN, NO_BTN, 0,
      true
   },

   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, KSK_UNKNOWN,
      KINGSN_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, KSK_UNKNOWN,
      KINGSN_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
#elif defined(DINGUX)
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, KSK_LALT,
      KS_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, KSK_LSHIFT,
      KS_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, KSK_ESCAPE,
      KS_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, KSK_RETURN,
      KS_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, KSK_UP,
      KS_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, KSK_DOWN,
      KS_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, KSK_LEFT,
      KS_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, KSK_RIGHT,
      KS_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, KSK_LCTRL,
      KS_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, KSK_SPACE,
      KS_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, KSK_TAB,
      KS_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, KSK_BACKSPACE,
      KS_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, KSK_PAGEUP,
      KS_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, KSK_PAGEDOWN,
      KS_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, KSK_KP_DIVIDE,
      KS_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, KSK_KP_PERIOD,
      KS_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_TRIGGER, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_RELOAD, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE, KSK_UNKNOWN,
      KINGSN_TURBO_ENABLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, KSK_UNKNOWN,
      KINGSN_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, KSK_UNKNOWN,
      KINGSN_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, KSK_UNKNOWN,
      KINGSN_VOLUME_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, KSK_UNKNOWN,
      KINGSN_VOLUME_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, KSK_UNKNOWN,
      KINGSN_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, KSK_UNKNOWN,
      KINGSN_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, KSK_UNKNOWN,  
      KINGSN_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, KSK_UNKNOWN,
      KINGSN_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, KSK_UNKNOWN,
      KINGSN_QUIT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, KSK_UNKNOWN,
      KINGSN_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, KSK_UNKNOWN,
      KINGSN_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, KSK_UNKNOWN,
      KINGSN_REWIND, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_BSV_RECORD_TOGGLE, KSK_UNKNOWN,
      KINGSN_BSV_RECORD_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, KSK_UNKNOWN,
      KINGSN_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, KSK_UNKNOWN,
      KINGSN_FRAMEADVANCE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, KSK_F5,
      KINGSN_RESET, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, KSK_UNKNOWN,
      KINGSN_SHADER_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, KSK_UNKNOWN,
      KINGSN_SHADER_PREV, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, KSK_UNKNOWN,
      KINGSN_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, KSK_UNKNOWN,
      KINGSN_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, KSK_UNKNOWN,
      KINGSN_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, KSK_UNKNOWN,
      KINGSN_SCREENSHOT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, KSK_UNKNOWN,
      KINGSN_MUTE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, KSK_UNKNOWN,
      KINGSN_OSK, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, KSK_UNKNOWN,
      KINGSN_FPS_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SEND_DEBUG_INFO, KSK_UNKNOWN,
      KINGSN_SEND_DEBUG_INFO, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, KSK_UNKNOWN,
      KINGSN_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, KSK_UNKNOWN,
      KINGSN_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, KSK_UNKNOWN,
      KINGSN_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, KSK_UNKNOWN,
      KINGSN_OVERLAY_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, KSK_UNKNOWN,
      KINGSN_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, KSK_UNKNOWN,
      KINGSN_DISK_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, KSK_UNKNOWN,
      KINGSN_DISK_PREV, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, KSK_UNKNOWN,
      KINGSN_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, KSK_UNKNOWN,
      KINGSN_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, KSK_UNKNOWN,
      KINGSN_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, KSK_HOME,
      KINGSN_MENU_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, KSK_UNKNOWN,
      KINGSN_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, KSK_UNKNOWN,
      KINGSN_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, KSK_UNKNOWN,
      KINGSN_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, KSK_UNKNOWN,
      KINGSN_AI_SERVICE, NO_BTN, NO_BTN, 0,
      true
   },
   
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, KSK_UNKNOWN,
      KINGSN_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, KSK_UNKNOWN,
      KINGSN_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
#else
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, KSK_l,
      KS_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, KSK_k,
      KS_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, KSK_q,
      KS_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   { 
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, KSK_e,
      KS_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, KSK_w,
      KS_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, KSK_s,
      KS_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, KSK_a,
      KS_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, KSK_d,
      KS_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, KSK_o,
      KS_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, KSK_i,
      KS_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, KSK_CAPSLOCK,
      KS_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, KSK_SEMICOLON,
      KS_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, KSK_TAB,
      KS_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, KSK_p,
      KS_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_TRIGGER, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_RELOAD, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE, KSK_UNKNOWN,
      KINGSN_TURBO_ENABLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, KSK_UNKNOWN,
      KINGSN_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, KSK_UNKNOWN,
      KINGSN_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, KSK_KP_PLUS,
      KINGSN_VOLUME_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, KSK_KP_MINUS,
      KINGSN_VOLUME_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, KSK_UNKNOWN,
      KINGSN_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, KSK_UNKNOWN,
      KINGSN_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, KSK_F11,  
      KINGSN_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, KSK_UNKNOWN,
      KINGSN_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
#ifdef HAVE_LAKKA
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RESTART_KEY, KSK_ESCAPE,
      KINGSN_QUIT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
#else
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, KSK_UNKNOWN,
      KINGSN_QUIT_KEY, NO_BTN, NO_BTN, 0,
      true
   },
#endif
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, KSK_UNKNOWN,
      KINGSN_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, KSK_UNKNOWN,
      KINGSN_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, KSK_UNKNOWN,
      KINGSN_REWIND, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_BSV_RECORD_TOGGLE, KSK_UNKNOWN,
      KINGSN_BSV_RECORD_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, KSK_UNKNOWN,
      KINGSN_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, KSK_UNKNOWN,
      KINGSN_FRAMEADVANCE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, KSK_F5,
      KINGSN_RESET, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, KSK_UNKNOWN,
      KINGSN_SHADER_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, KSK_UNKNOWN,
      KINGSN_SHADER_PREV, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, KSK_UNKNOWN,
      KINGSN_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, KSK_UNKNOWN,
      KINGSN_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, KSK_UNKNOWN,
      KINGSN_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, KSK_UNKNOWN,
      KINGSN_SCREENSHOT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, KSK_UNKNOWN,
      KINGSN_MUTE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, KSK_UNKNOWN,
      KINGSN_OSK, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, KSK_UNKNOWN,
      KINGSN_FPS_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SEND_DEBUG_INFO, KSK_UNKNOWN,
      KINGSN_SEND_DEBUG_INFO, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, KSK_UNKNOWN,
      KINGSN_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, KSK_UNKNOWN,
      KINGSN_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, KSK_UNKNOWN,
      KINGSN_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, KSK_UNKNOWN,
      KINGSN_OVERLAY_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, KSK_UNKNOWN,
      KINGSN_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, KSK_UNKNOWN,
      KINGSN_DISK_NEXT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, KSK_UNKNOWN,
      KINGSN_DISK_PREV, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, KSK_UNKNOWN,
      KINGSN_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, KSK_UNKNOWN,
      KINGSN_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, KSK_UNKNOWN,
      KINGSN_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, KSK_ESCAPE,
      KINGSN_MENU_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, KSK_UNKNOWN,
      KINGSN_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, KSK_UNKNOWN,
      KINGSN_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, KSK_UNKNOWN,
      KINGSN_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, KSK_UNKNOWN,
      KINGSN_AI_SERVICE, NO_BTN, NO_BTN, 0,
      true
   },

   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, KSK_UNKNOWN,
      KINGSN_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, KSK_UNKNOWN,
      KINGSN_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0,
      true
   },
#endif
};

/* Users 2 to MAX_USERS */
static const struct ks_keybind ks_keybinds_rest[] = {
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, KSK_KP3,
      KS_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, KSK_KP2,
      KS_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, KSK_RSHIFT,
      KS_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, KSK_RETURN,
      KS_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, KSK_UP,
      KS_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, KSK_DOWN,
      KS_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, KSK_LEFT,
      KS_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, KSK_RIGHT,
      KS_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, KSK_KP6,
      KS_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, KSK_KP5,
      KS_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, KSK_KP8,
      KS_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, KSK_KP9,
      KS_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, KSK_UNKNOWN,
      KS_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, KSK_UNKNOWN,
      KINGSN_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_TRIGGER, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_RELOAD, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_START, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, KSK_UNKNOWN,
      KINGSN_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0,
      true
   },
   {
      NULL, NULL,
      AXIS_NONE, AXIS_NONE, AXIS_NONE,
      MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE, KSK_UNKNOWN,
      KINGSN_TURBO_ENABLE, NO_BTN, NO_BTN, 0,
      true
   },
};

#endif

#endif
